---
# tasks file for ansible-vagrant-box
- name: Install python
  become: yes
  become_method: sudo
  raw: test -e /usr/bin/python || (apt-get update -qq && apt-get upgrade -qq && apt-get install -qq python-minimal python3 python3-apt aptitude  > /dev/null)
  register: output
  changed_when:
    - output.stdout != ""
    - output.stdout != "\r\n"

- name: Update to the latest packages
  become: yes
  become_method: sudo
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install python3 and dependencies
  become: yes
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - 'aptitude'
    - 'python3'
    - 'python3-apt'
    - 'python3-pip'
    - 'python3-venv'
    - 'build-essential'
    - 'pwgen'
    - 'rsyslog-gnutls'

- name: Upgrade Pip and Wheel
  become: yes
  become_method: sudo
  pip:
    executable: pip3
    name: "{{ item }}"
    state: latest
  with_items:
    - 'pip'
    - 'wheel'
    - 'docker-py'

- name: Include /vagrant/bin in path
  become: yes
  become_method: sudo
  lineinfile:
    path: .profile
    state: present
    line: 'PATH="$PATH:/vagrant/bin"'

- name: Write HOST_IP ENV to .profile
  become: yes
  become_method: sudo
  lineinfile:
    path: ~/.profile
    state: present
    line: "export HOST_IP={{ ansible_default_ipv4.address }}"

- name: Download papertrails certs
  become: yes
  become_method: sudo
  get_url:
    url: "https://papertrailapp.com/tools/papertrail-bundle.pem"
    dest: /etc/papertrail-bundle.pem

- name: Set rsyslog.conf
  become: yes
  become_method: sudo
  blockinfile:
    path: /etc/rsyslog.conf
    state: present
    block: |
      $DefaultNetstreamDriverCAFile /etc/papertrail-bundle.pem # trust these CAs
      $ActionSendStreamDriver gtls # use gtls netstream driver
      $ActionSendStreamDriverMode 1 # require TLS
      $ActionSendStreamDriverAuthMode x509/name # authenticate by hostname
      $ActionSendStreamDriverPermittedPeer *.papertrailapp.com
      *.*                       @@{{ papertrail_server }}.papertrailapp.com:{{ papertrail_port }}
  notify: "restart rsyslog"
